name: repradar
description: "Fitness tracking app."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.0.0
  google_sign_in: ^6.1.5
  crypto: ^3.0.3

  http: ^1.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  dio: ^5.9.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env # <-- Add this line
    - lib/assets/images
