"""Describe schema change here

Revision ID: 5e327cac0d8c
Revises: cb79b3facc2c
Create Date: 2025-10-11 15:53:28.979918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e327cac0d8c'
down_revision: Union[str, None] = 'cb79b3facc2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('history', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('history', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'created_at')
    op.drop_column('history', 'score')
    op.drop_column('history', 'user_id')
    # ### end Alembic commands ###
